version: "3"

services: 
  server:
    build: ./server
    expose: 
      - 8000
    ports:
      - '80:8000'
    volumes:
      - ./server  
    command: npm start

  client:
    build: ./client 
    expose:
      - 80
    ports:
      - '8080:80'
    volumes:
      - ./build
    links:
      - server      